### ISSUE TITLE
Broken link 'more ...'

### ISSUE THREAD

**Issue by songproducer** [Leo-ajc/ProTip#2]
chrome-extension://obpohohcmdaklmaagjgdaldgjhohegak/views/recommendation.html
<img width="254" alt="screen shot 2015-10-09 at 3 36 29 am" src="https://cloud.githubusercontent.com/assets/597346/10377617/fb3460ac-6e36-11e5-94e5-944c72dc0aa3.png">

**Comment by songproducer** [comment]
Also how do I become an early adopter?

**Comment by Leo-ajc** [comment]
Thanks Songproducer!

Fixed. I have added it to the release I am currently working on. It should be out in the next 5 days.

Please send me your URL and a 64x64 pixel image, I'll add it to the release.
