### ISSUE TITLE
Expand default "Ignore" list

### ISSUE THREAD

**Issue by bnvk** [Leo-ajc/ProTip#22]
Currently, the **Ignore** functionality of ProTip stops the extension from analyzing the following sites by default:

- bitfinex.com
- bitstamp.net
- blockchain.info
- blockexplorer.com
- btc-e.com
- google.com
- insight.bitpay.com

As the crypto currency space has grown tremendously since 2015, and this list is rather small to begin with, seems like it would be good to add a bunch more domains that create false positives such as:

- bitcoin.com
- wallet.bitcoin.com
- circle.com
- coinbase.com
- kraken.com
- ledgerwallet.com
- poloniex.com
- trezor.io

@Enegnei perhaps you want to contribute somewhere?

**Comment by Enegnei** [comment]
I would also add: archive sites, scam sites, block explorers, wallets / exchanges, etc. 

- archive.is
- archive.org
- bitconnect.co
- bitcoinmillions.co
- bittrex.com
- www.blockcypher.com / live.blockcypher.com
- www.blockexperts.com
- www.blocktrail.com
- www.btcc.com
- edgesecure.co
- www.poloniex.com

**Comment by Enegnei** [comment]
Crypto related:

- www.altcoin.io
- cex.io

Search engines:

- www.baidu.com
- www.bing.com
- duckduckgo.com
- search.yahoo.com
- www.startpage.com

**Comment by Enegnei** [comment]
Search engines:

- https://www.baidu.com/
- https://www.bing.com
- https://duckduckgo.com/
- https://search.yahoo.com/
- https://www.startpage.com/

**Comment by bnvk** [comment]
This was done!
