### ISSUE TITLE
bitconnectcoin Not yet redeemed

### ISSUE THREAD

**Issue by martinsts** [Leo-ajc/ProTip#24]
please help my bitconnectcoin have been Not yet redeemed when I send to my wallet. I send my bcc from coinexchange to my wallet bitconnect . who can help me?
https://chainz.cryptoid.info/bcc/tx.dws?45660c69da781d2a0a1595839de907a9461c27cbe617d43e01cf00b9c40a2705.htm

**Comment by bnvk** [comment]
Does not related to ProTip. Good luck resolving your issue.
