### ISSUE TITLE
bitcoin:// Links not always get picked up

### ISSUE THREAD

**Issue by m0se** [Leo-ajc/ProTip#4]
Maybe this is a issue with validation, I was not able to reproduce that, but I tried running the part of the code that searches for bitcoin:// Links (from content.js line 99-109) in the browser console and the address was found. Only the ProTip icone stays gray and dose not pickup the address.

![image](https://cloud.githubusercontent.com/assets/2543808/10843567/111b4538-7efa-11e5-9ccc-c4693a38fbe4.png)

That's the site I had the issue with (german newspaper):
http://www.taz.de/Aufweichung-der-Netzneutralitaet/!5246903/

I had this issue several times on other pages to, but that's the first time I looking into it.

**Comment by Leo-ajc** [comment]
Thanks m0se,

I understand this problem. 

ProTip recognises the format. I checked it here.

http://leocampbell.net/protip/protipTest.html 

ProTip scans the page when the webpage initially loads. The bitcoin link is dynamically loaded after the page has loaded.

```
<a href="bitcoin:165dtfwNvyMUbLGdqf87w8DfZX7i542Fyr?label=taz%20zahl%20ich" target="_blank" style="color:#961D2A;">165dtfwNvyMUbLGdqf87w8DfZX7i542Fyr</a>
``` 
I need to make ProTip listen to the MutationObserver.
https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver

Thanks M0se, I'll be adding it to the next release.
