### ISSUE TITLE
Network Error: https://blockchain.info/pushtx is unreachable. Please try again later.

### ISSUE THREAD

**Issue by bananenwilly** [Leo-ajc/ProTip#5]
You will be donating to all the websites listed in the table below.
You can quickly remove any websites from the list by clicking the .
All your previous web browsing data will be wiped clear.
Yes, please send my donations now! 

Network Error: https://blockchain.info/pushtx is unreachable. Please try again later.

**Comment by Leo-ajc** [comment]
Thanks Bannanenwilly,

I know that bug. It relates to various problems with communicating with a bitcoin network API. We have rewritten a lot of code to make it more stable. We have a release candidate, v1.0.0.31, out for testing at the moment. We hope to update the Chrome Store v1.0.0.15 in the next couple of days.

If you would like to test the release candidate, that would be great. However, please remember to save your private key.

https://chrome.google.com/webstore/detail/protip-staging-release-ca/colfmikdmcblkhmlpecjipokfnbgkmci
